lazyrules
VasylPosmit/training-2022-09 pull request #12
Opened 2022-09-29 14:41 UTC by celpjmnz

2022-09-29 14:51 UTC, VasylPosmit requested changes

2022-09-29 14:51 UTC, VasylPosmit commented on index.js
> +    return console.log("Just numbers");
use return OR console.log

2022-09-29 14:51 UTC, VasylPosmit commented on index.js
> +        let resF = res.toFixed();
Requirements are 
- if precise answer is fractions, than return "something around [number]"

2022-09-30 11:40 UTC, VladimirGOU approved these changes

2022-09-30 11:42 UTC, VladimirGOU commented on index.js
> -//pull request
can we delete this comment?

2022-09-30 11:47 UTC, TGacek89 approved these changes

2022-09-30 11:47 UTC, TGacek89 commented on index.js
> +}
Nice

2022-10-03 12:56 UTC, closed without merging