Task 11 fibonacci
VasylPosmit/training-2022-09 pull request #14
Opened 2022-09-29 15:34 UTC by VladimirGOU

2022-09-30 07:17 UTC, TGacek89 approved these changes

2022-09-30 10:54 UTC, VasylPosmit requested changes

2022-09-30 10:54 UTC, VasylPosmit commented on index.js
> +for (let i = 1; i <= number; i++) {
We need a method to use

2022-09-30 10:54 UTC, VasylPosmit commented on index.js
> +for (let i = 1; i <= number; i++) {
Otherwise it can not be tested or used

2022-09-30 11:14 UTC, celpjmnz approved these changes

2022-09-30 11:40 UTC, VasylPosmit commented on index.js
> -alert("HELLO ITS MY FIRST COMMIT");
good that you've deleted unused code
It follows YAGNI

2022-09-30 11:44 UTC, celpjmnz commented on index.js
> +}}
Good function

2022-09-30 11:45 UTC, VladimirGOU commented on index.js
> +}}
Thanks)

2022-10-03 11:51 UTC, TGacek89 reviewed
Comment the fibonacchi on line 65

2022-10-03 11:55 UTC, celpjmnz approved these changes

2022-10-03 12:06 UTC, TGacek89 approved these changes

2022-10-03 12:17 UTC, celpjmnz approved these changes

2022-10-03 12:28 UTC, merged